name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman contribution graph
        uses: Platane/snk@v3
        with:
          github_user_name: guilhermefelype
          outputs: |
            ./output/pacman-contribution-graph.svg?palette=github-light&color_snake=#8b5cf6
            ./output/pacman-contribution-graph-dark.svg?palette=github-dark&color_snake=#8b5cf6

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/
          git commit -m "update contribution graph" || echo "no changes"
          git push
